name: Build latest release

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1

jobs:
  prepare:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.vars.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest tag
        id: vars
        run: |
          LATEST_TAG=$(gh release list --limit 1 --repo zed-industries/zed --exclude-drafts --exclude-pre-releases --json tagName --jq '.[0].tagName')
          echo "Latest tag: $LATEST_TAG"
          echo "tag=${LATEST_TAG}" >> "$GITHUB_OUTPUT"

      - name: Check latest tag
        id: check_tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          TAG_EXISTS=$(git tag -l "${{ steps.vars.outputs.tag }}")
          if [ -z "$TAG_EXISTS" ]; then
            echo "Tag does not exist."
          else
            echo "Tag exists."
            exit 1
          fi

  build:
    runs-on: windows-latest

    needs: prepare

    steps:
      - run: echo "Proceeding with the build as the tag does not exist."
      - run: echo ${{needs.prepare.outputs.tag}}
